var http = require('http');

var server = http.createServer(function(request, response) {
  console.log('got a request!');
  let data = {
    "Maybelline": [{
      "name": "Master Chrome Metallic Highlighter",
      "price": "$9.99",
      "image_link": "https://images-na.ssl-images-amazon.com/images/I/81MCLt7hILL._SY355_.jpg",
      "website_link": "https://www.maybelline.com/face-makeup/contouring/facestudio-master-chrome-metallic-highlighter",
      "description": "Heat up your look with a warm metallic sheen. Features reflective pigments for an eye-catching chrome effect.",
      "rating": 4.6,
    }, {
      "name": "Fit Me! Matte + Poreless Foundation",
      "price": "$7.99",
      "image_link": "https://i5.walmartimages.com/asr/99691068-0ebf-4ced-89a2-8e559a6171fc_1.1ee11f746dbc5ba0388b167afafb5b53.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF",
      "website_link": "https://www.maybelline.com/face-makeup/foundation-makeup/fit-me-matte-poreless-foundation",
      "description": "Want the perfect foundation fit? It's all about matching skin tone and texture. Mattifying liquid formula ideal for normal to oily skin.",
      "rating": 4.4,
    }, {
      "name": "SuperStay Matte Ink Lipstick",
      "price": "$9.49",
      "image_link": "https://www.maybelline.com/~/media/mny/global/lips-makeup/lip-color/super-stay-matte-ink-liquid-lipstick/maybelline-lip-color-super-stay-matte-ink-loyalist-041554496895-o.jpg",
      "website_link": "https://www.maybelline.com/lip-makeup/lipstick/superstay-matte-ink-liquid-lipstick",
      "description": "Intensely perfect, perfectly intense. Ink your lips in up to 16 HR saturated liquid matte.",
      "rating": 4.4,
    }, {
      "name": "Lash Sensational Washable Mascara",
      "price": "$8.99",
      "image_link": "https://www.superdrug.com/medias/sys_master/side-zoom/side-zoom/8899744956446/Maybelline-Lash-Sensational-Mascara-Very-Black-1-348705.jpg",
      "website_link": "https://www.maybelline.com/eye-makeup/mascara/lash-sensational-washable-mascara",
      "description": "Lash Sensational Mascara from Maybelline is the first patented fanning brush with 10 layers of bristles to reveal a full flourish of lashes. Liquid Ink formula coats from all sides for a sensational full fan effect.",
      "rating": 4.2,
    }, {
      "name": "Eye Studio Lasting Drama Gel Eyeliner",
      "price": "$9.99",
      "image_link": "https://images-na.ssl-images-amazon.com/images/I/71hI8EJGy0L._SL1500_.jpg",
      "website_link": "https://www.maybelline.com/eye-makeup/eyeliner/eyestudio-lasting-drama-gel-eyeliner",
      "description": "The most intense line for lasting drama. Maybelline Eye Studio Lasting Drama Gel Eyeliner holds highly concentrated pigments in a clear gel base, so color is more intense and lines resist wear for 24 hours.",
      "rating": 4.0,
    }, ],
    "NYX": [{
      "name": "Mirco Brow Pencil",
      "price": "$10.00",
      "image_link": "https://www.nyxcosmetics.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-cpd-nyxusa-master-catalog/default/dw71319750/ProductImages/Eyes/Micro_Brow_Pencil/800897836894_microbrowpencil_espresso_main.jpg?sw=420&sh=420&sm=fit",
      "website_link": "http://www.nyxcosmetics.com/micro-brow-pencil/NYX_181.html?cgid=root",
      "description": "Build full beautiful brows with our ultra-thin Micro Brow Pencil. So precise it coats even the finest hairs with color for a natural-looking finish.",
      "rating": 4.6,
    }, {
      "name": "Matte Finish Makeup Setting Spray",
      "price": "$8.00",
      "image_link": "https://scbeautyhigh.files.wordpress.com/2013/03/screen-shot-2013-03-08-at-4-42-13-pm.png?w=342&h=515",
      "website_link": "http://www.nyxcosmetics.com/makeup-setting-spray-matte/NYX_094.html?cgid=root",
      "description": "Demand perfection! For that fresh makeup look that lasts, the Makeup Setting Spray - Matte is a gorgeous shine-free matte finish that is lightweight and comfortable while working hard to make sure your makeup stays put.",
      "rating": 4.5,
    }, {
      "name": "Ultimate Eyeshadow Pallete",
      "price": "$18.00",
      "image_link": "http://images.ulta.com/is/image/Ulta/2301917",
      "website_link": "http://www.nyxcosmetics.com/ultimate-shadow-palette/800897017644.html",
      "description": "We named this collection the Ultimate Shadow Palette because that’s exactly what it is—a pro-level palette packed with 16 high-performance eyeshadows and pressed pigments in a rainbow of tone-inspired shades. Available in four striking color combinations—Neutral-Cool, Neutral-Warm, Bright and Smokey/Highlight—each set features a vivid mix of velvety-rich textures and mesmerizing finishes that range from mattes and satins to shimmers and metallics.",
      "rating": 4.6,
    }, {
      "name": "Total Control Drop Foundation",
      "price": "$14.00",
      "image_link": "http://kremmania.hu/uploadedimages/22/nyx-total-control-drop-foundations9-300-300.png",
      "website_link": "http://www.nyxcosmetics.com/total-control-drop-foundation/NYX_413.html?cgid=root",
      "description": "From sheer to full, your ideal coverage is just drops away with our new Total Control Drop Foundation! Fine-tune this velvety, matte foundation with the included dropper. Simply adjust the number of drops until you create the look you’re feelin’ today. Want more coverage? Add more drops! Buff expertly using the TOTAL CONTROL DROP FOUNDATION BRUSH for a seriously smooth finish.",
      "rating": 4.2,
    }, {
      "name": "Angel Veil Skin Perfecting Primer",
      "price": "$16.00",
      "image_link": "https://media.littlewoodsireland.ie/i/littlewoodsireland/6L3FR_SQ1_0000000088_NO_COLOR_SLf?$266x354_standard$",
      "website_link": "http://www.nyxcosmetics.com/angel-veil-skin-perfecting-primer/800897828837.html",
      "description": "This super silky, light and fresh formula creates a comfortable cushion on your skin to enhance makeup application. The incredible formula creates a smooth uniform canvas that minimizes shine and makes application flawless. Your skin will feel like it has been touched by an angel.",
      "rating": 4.3,
    }, ],
    "Covergirl": [{
      "name": "LashBlast Volume Mascara",
      "price": "$8.99",
      "image_link": "https://cc2covergirl-res.cloudinary.com/image/upload/s--gcQqbgK7--/f_auto,fl_lossy,q_auto:good,w_580/v1/stage/Covergirl_LashBlastVolumeMascara_22700097784_Black_01.jpg",
      "website_link": "https://www.covergirl.com/en_us/beauty-products/eye-makeup/mascara/lashblast-volumizing-mascara",
      "description": "Get a blast of bold, volumizing mascaras! LashBlast's patented volume-boosting hypoallergenic mascara formula and patent-pending brush are designed to max out each and every lash, leaving you with the ultimate big-lash look. Now in waterproof, too!",
      "rating": 4.4,
    }, {
      "name": "Roses TruNaked Eyeshadow Palette",
      "price": "$9.99",
      "image_link": "https://cc2covergirl-res.cloudinary.com/image/upload/s--9_N9DCgX--/f_auto,fl_lossy,q_auto:good,w_580/v1/stage/Covergirl_truNakedEyeShadow_22700581139_Roses_01_0.jpg",
      "website_link": "https://www.covergirl.com/en_us/beauty-products/eye-makeup/eyeshadow/trunaked-eyeshadow-palettes",
      "description": "TruNaked eyeshadow palettes feature universally flattering, neutral shades that are made to be blended together, so you can mix and match colors and always look flawless. Each eye shadow palette comes with 8 highly pigmented shades, and endless possibilities.",
      "rating": 4.3,
    }, {
      "name": "LashBlast Fusion Mascara",
      "price": "$8.99",
      "image_link": "https://cc2covergirl-res.cloudinary.com/image/upload/s--PNYFE3bU--/f_auto,fl_lossy,q_auto:good,w_580/v1/stage/Covergirl_LashBlastFusionVolumizingLengtheningMascara_22700127047_VeryBlack_01_0.jpg",
      "website_link": "https://www.covergirl.com/en_us/beauty-products/eye-makeup/mascara/lashblast-fusion-mascara",
      "description": "The fiberstretch formula and oversized brush make every little lash bigger, fuller, longer-looking, and more dramatic. Also available in Water Resistant!",
      "rating": 4,
    }, {
      "name": "Clean Matte BB Cream",
      "price": "$7.99",
      "image_link": "https://cc2covergirl-res.cloudinary.com/image/upload/s--EBgKEGmN--/f_auto,fl_lossy,q_auto:good,w_580/v1/stage/Covergirl_CleanMatteBBCream_22700251155_MediumDeep_01.jpg",
      "website_link": "https://www.covergirl.com/en_us/beauty-products/face-makeup/foundation-makeup/clean-matte-bb-cream",
      "description": "Clean Matte BB Cream is an oil-free formula that provides the perfect amount of coverage to even skin tone, hide blemishes, won’t clog pores and keeps you shine-free.",
      "rating": 4.4,
    }, {
      "name": "Perfect Point Plus Eyeliner",
      "price": "$6.99",
      "image_link": "https://cc2covergirl-res.cloudinary.com/image/upload/s--33DCcSCy--/f_auto,fl_lossy,q_auto:good,w_580/v1/stage/Covergirl_PerfectPointPlusEyelinerPencil_22700250967_HunterGreen_01.jpg",
      "website_link": "https://www.covergirl.com/en_us/beauty-products/eye-makeup/eyeliner/perfect-point-plus-eyeliner",
      "description": "This eyeliner pencil gives you control and versatility. Want a precise line? It glides on easily. Want to soften a bit? There's a soft smudger tip. Best of all? No sharpening necessary. It's got a specially designed self-sharpener inside. So you always get the point–perfectly.",
      "rating": 4.2,
    }, ],
    "L'Oreal Paris": [{
      "name": "Voluminous Lash Paradise Washable Mascara",
      "price": "$9.99",
      "image_link": "https://img.makeupalley.com/hwthumb/980/980/2_9_3_5_3196465.JPG",
      "website_link": "https://www.lorealparisusa.com/products/makeup/eye/mascara/voluminous-lash-paradise-waterproof-mascara.aspx?shade=203-black",
      "description": "Take your lashes to paradise! Our 1st mascara for voluptuous volume & length. Soft wavy bristle brush holds maximum formula for a dramatic volumizing charge. 200+ bristles catch every lash for a full fringe effect. Smooth glide formula provides silky volume in one coat. Lashes are feathery soft to the touch. Women agreed: 91% saw intense & volumized lashes and 87% saw more beautiful lashes. +98% lengthening effect.",
      "rating": 4.3,
    }, {
      "name": "Telescopic Carbon black Mascara",
      "price": "$10.59",
      "image_link": "https://i.pinimg.com/736x/3e/c1/04/3ec1043723cd7388127d9e8031d8423c--loreal-telescopic-mascara-carbon-black.jpg",
      "website_link": "https://www.lorealparisusa.com/products/makeup/eye/mascara/telescopic-carbon-black-mascara-carbon-black.aspx?shade=carbon-black",
      "description": "L'Oréal's Telescopic Carbon Black Mascara features a patented no clump brush that applies the mascara precisely for long, perfectly defined lashes. Removes easily with soap and water. Ophthalmologist tested. Allergy tested. Suitable for those with sensitive eyes and contact lens wearers. Fragranc",
      "rating": 4.3,
    }, {
      "name": "Infallible Pro-Matte 24HR Foundation",
      "price": "$12.99",
      "image_link": "http://images.ulta.com/is/image/Ulta/2283481?$detail$",
      "website_link": "https://www.lorealparisusa.com/products/makeup/face/foundation-makeup/infallible-pro-matte-foundation.aspx?shade=classic-ivory-101",
      "description": "L'Oréal's Infallible Pro-Matte 24HR Foundation has an air-light texture with a demi-matte finish. This super gliding mattifying formula has a high water content for maximum comfort that lasts!",
      "rating": 4.1,
    }, {
      "name": "Brow Stylist Definer",
      "price": "$8.99",
      "image_link": "http://images.ulta.com/is/image/Ulta/2510087?$lg$",
      "website_link": "https://www.lorealparisusa.com/products/makeup/eye/eyebrow/brow-stylist-definer.aspx?shade=blonde",
      "description": "L'Oreal's Brow Stylist Definer makes the art of the brow made easy! Shape brows with this ultra-fine 0.5mm pencil tip - a perfect tool to recreate tiny brow hair and allowing you to precisely draw and shape your brows for a well-defined look. This mechanical and retractable pencil has a spoolie brush for combing and blending the perfect brow.",
      "rating": 4.2,
    }, {
      "name": "Infallible Pro-Matte Liquid Lipstick",
      "price": "$9.99",
      "image_link": "https://target.scene7.com/is/image/Target/17478994_Alt03?wid=520&hei=520&fmt=pjpeg",
      "website_link": "https://www.lorealparisusa.com/products/makeup/lip-color/lipstick/infallible-pro-matte-liquid-lipstick.aspx?shade=352-shake-down",
      "description": "The Pro-Matte Sensation: Introducing Infallible Pro-Matte Liquid Lipstick, L'Oreal's first up to 16 hour matte liquid lipstick! Intense high pigment shades create comfortable, lasting ultra-matte color. This long-wearing, full-coverage liquid lip feels light for all day comfort. With the pro-sculpt applicator, shape and add dimension to lips.",
      "rating": 4.5,
    }, ],
    "Revlon": [{
      "name": "ColorStay Makeup For Combo/Oily S",
      "price": "$12.99",
      "image_link": "https://i5.walmartimages.ca/images/Large/410/013/999999-309975410013.jpg?odnBound=460",
      "website_link": "http://www.revlon.com/products/face/foundation-makeup/colorstay-makeup-combination-oily-skin#309975410013||0",
      "description": "America’s #1 longwear foundation, now with a mess-free pump and SPF protection. In 35 shades for every skin tone and type. Flawless, matte coverage that lasts up to 24 hours. Comfortable, lightweight formula specifically made for combination or oily skin to control oil absorption and shine.",
      "rating": 4.2,
    }, {
      "name": "Ultra HD Matte Lip Color",
      "price": "$9.99",
      "image_link": "https://m.media-amazon.com/images/S/aplus-media/vc/4f72a843-9256-497a-aac4-e022404e8a86._SR300,300_.jpg",
      "website_link": "http://www.revlon.com/products/lips/lip-color/revlon-ultra-hd-matte-lipcolor-metallic-matte-finish#309974372213||0",
      "description": "Revlon's Ultra HD Matte Lip Color is a lightweight, high definition, matte color with a moisturizing velvety feel.",
      "rating": 4.1,
    }, {
      "name": "Super Lustrous Lipstick",
      "price": "$8.49",
      "image_link": "https://i.ebayimg.com/images/g/d6sAAOSwZtJW8v64/s-l300.jpg",
      "website_link": "http://www.revlon.com/products/lips/lip-color/revlon-super-lustrous-lipstick#309974877046||0",
      "description": "Revlon's Super Lustrous Lipstick is infused with silk and vitamins for smooth, conditioning color. In a dazzling array of fabulous, fashionable shades.",
      "rating": 4.3,
    }, {
      "name": "Revlon ColorStay Eye Liner",
      "price": "$8.99",
      "image_link": "https://img.makeupalley.com/2/8/4/0/846864.JPG",
      "website_link": "http://www.revlon.com/products/eyes/eyeliner/revlon-colorstay-eyeliner#309973978010||0",
      "description": "Revlon ColorStay Eye Liner glides on easily adding drama and definition to your eyes for up to 16 hours. Waterproof formula won't smear, smudge or fade.",
      "rating": 4.2,
    }, {
      "name": "Kiss Balm Lip Balm",
      "price": "$4.99",
      "image_link": "http://images.revlon.com/~/media/images/revlon2/product-shade-images/309977824108.ashx",
      "website_link": "http://www.revlon.com/products/lips/lip-care/revlon-kiss-balm#309977824108||0",
      "description": "Revlon Kiss Balm Lip Balm is ultra hydrating lip care that provides instantly softer, smoother, kissable lips. The hydrating formula is infused with natural fruit oils, in sheer juicy color and comes with SPF 20 protection.",
      "rating": 4.7,
    }, ],
    "Tarte": [{
      "name": "Shape tape contour concealer",
      "price": "$25.00",
      "image_link": "https://img.makeupalley.com/1/1/8/1/3031818.JPG",
      "website_link": "https://tartecosmetics.com/en_US/makeup/face/concealer/shape-tape-contour-concealer/836.html?dwvar_836_color=light-medium&cgid=#q=shape%2Btape&lang=en_US&start=5",
      "description": "Provides a flawless matte finish that won’t flake or crease, even if you have dry skin, fine lines, or pore problems – no setting powder necessary. Mango seed & shea butters naturally regenerate & illuminate all complexions, letting you play with light to lift your features.",
      "rating": 4.6,
    }, {
      "name": "Amazonian Clay 12-Hour Full Coverage Foundation SPF 15",
      "price": "$39.00",
      "image_link": "https://images-na.ssl-images-amazon.com/images/I/41qQ0JVILtL._AC_UL320_SR240,320_.jpg",
      "website_link": "https://tartecosmetics.com/en_US/makeup/face/foundation/amazonian-clay-12-hour-foundation-spf-15/267.html?dwvar_267_color=ivory&cgid=#q=Amazonian%2BClay%2B12-Hour%2BFull%2BCoverage%2BFoundation%2BSPF%2B15&lang=en_US&start=1",
      "description": "Provides a natural matte finish & oil control for flawless longwear without clogging pores or sinking into lines in a cake-free & comfortable formula. It covers redness, acne, & hyperpigmentation without hiding your complexion. This vitamin- & Amazonian clay-rich foundation formula restores balance to help improve your skin even when you’re not wearing it, & SPF 15 provides broad spectrum protection.",
      "rating": 4.4,
    }, {
      "name": "Lights, Camera, Lashes Precision Longwear Liquid Eyeliner",
      "price": "$20.00",
      "image_link": "http://images.ulta.com/is/image/Ulta/2273773?$detail$",
      "website_link": "https://tartecosmetics.com/en_US/makeup/eyes/eyeliner/lights-camera-lashes-precision-longwear-liquid-eyeliner/528.html?dwvar_528_color=black&cgid=#q=Lights%2C%2BCamera%2C%2BLashes%2BPrecision%2BLongwear%2BLiquid%2BEyeliner&lang=en_US&start=1",
      "description": "A revolutionary extension of everyone’s favorite lights, camera, lashes™ line, the triple black formula delivers the ultimate in precision pigment for a rich definition that lasts. Powered by provitamin B5, it helps to moisturize & soothe the skin while thickening the appearance of lashes. The foolproof design, complete with an easy-hold grip, allows the liner to seamlessly glide & fill in spaces, without any skipping, smudging or pulling. Simply trace the ultra-thin, flexible tip along the lash line to create tight, crisp lines or the bolder, more dramatic looks you desire. ",
      "rating": 4,
    }, {
      "name": "Double Duty Beauty Empowered Hybrid Gel Foundation",
      "price": "$39.00",
      "image_link": "http://images.ulta.com/is/image/Ulta/2300329?$detail$",
      "website_link": "https://tartecosmetics.com/en_US/makeup/face/foundation/empowered-hybrid-gel-foundation/757.html?dwvar_757_color=fair-light%20neutral&cgid=#q=Double%2BDuty%2BBeauty%2BEmpowered%2BHybrid%2BGel%2BFoundation&lang=en_US&start=1",
      "description": "Smooth skin is in with this radiant, full coverage foundation with skin-loving ingredients wrapped in a luxurious, creamy gel. The unique, oil-free blend of smoothing, plumping & pore refining ingredients help brighten skin while moisturizing & blurring the look of fine lines & pores.",
      "rating": 3.9,
    }, {
      "name": "Tartelette 2 In Bloom Clay Eyeshadow Palette",
      "price": "$45.00",
      "image_link": "http://qvc.scene7.com/is/image/QVC/a/78/a356778.001?$uspdlarge$",
      "website_link": "https://tartecosmetics.com/en_US/collections/amazonian-clay/tartelette-in-bloom-clay-palette/712.html?dwvar_712_color=multi&cgid=#q=Tartelette%2B2%2BIn%2BBloom%2BClay%2BEyeshadow%2BPalette&lang=en_US&start=1",
      "description": "Warm-toned assortment of 9 mattes & 3 delicate shimmers ranging from soft nudes to deep chocolates are arranged in rows for 3 easy looks that you’ll wear every day. The superblendable Amazonian clay-infused powder formula glides on like a cream, providing longwearing, intense payoff that’s never chalky or patchy",
      "rating": 4,
    }, ],
    "MAC": [{
      "name": "Prep + Prime Fix +",
      "price": "$25.00",
      "image_link": "http://www.maccosmetics.com/media/export/cms/products/640x600/mac_sku_MW5K01_640x600_0.jpg",
      "website_link": "http://www.maccosmetics.com/product/13825/32212/products/skincare/primers/prep-prime-fix",
      "description": "A lightweight water mist that gently soothes and refreshes skin and finishes makeup.",
      "rating": 4.6,
    }, {
      "name": "Studio Fix Powder Plus Foundation",
      "price": "$29.00",
      "image_link": "http://www.maccosmetics.com/media/export/cms/products/640x600/mac_sku_M51021_640x600_1.jpg",
      "website_link": "http://www.maccosmetics.com/product/13847/251/products/makeup/face/foundation/studio-fix-powder-plus-foundation#/shade/NC20",
      "description": "A one-step powder and foundation that provides a matte texture with medium to full coverage.",
      "rating": 4.7,
    }, {
      "name": "Studio Fix Fluid SPF 15 Foundation",
      "price": "$29.00",
      "image_link": "http://www.maccosmetics.com/media/export/cms/products/640x600/mac_sku_M6JC02_640x600_0.jpg",
      "website_link": "http://www.maccosmetics.com/product/13847/1231/products/makeup/face/foundation/studio-fix-fluid-spf-15#/shade/NC20",
      "description": "An oil-controlling formula that offers a matte finish with medium to full coverage.",
      "rating": 4.3,
    }, {
      "name": "Lipstick Matte",
      "price": "$17.50",
      "image_link": "https://n.nordstrommedia.com/ImageGallery/store/product/Zoom/11/_100878451.jpg?crop=pad&pad_color=FFF&format=jpeg&w=587&h=900",
      "website_link": "http://www.maccosmetics.com/product/13854/310/products/makeup/lips/lipstick/matte-lipstick#/shade/Chili",
      "description": "A creamy rich Lipstick formula with high colour payoff in a no-shine matte finish.",
      "rating": 4,
    }, {
      "name": "Pro Longwear Paint Pot",
      "price": "$22.00",
      "image_link": "https://images-na.ssl-images-amazon.com/images/I/31HZ1-zMKvL._SY355_.jpg",
      "website_link": "http://www.maccosmetics.com/product/13840/1573/products/makeup/eyes/shadow/pro-longwear-paint-pot#/shade/Painterly",
      "description": "A long-wearing blendable cream shadow that can be worn alone or with other products.",
      "rating": 4.5,
    }, ],
    "Anatasia Beverly Hills": [{
      "name": "Liquid Lipstick",
      "price": "$20.00",
      "image_link": "http://www.anastasiabeverlyhills.com/dw/image/v2/BBLL_PRD/on/demandware.static/-/Sites-anastasia-master-catalog/default/dw1db2e32f/images/2017%20New%20Logo/LIPS/Liquid%20Lipstick/ABH01-32107-dazed/abh-dazed-liquid-lipstick-off.jpg?sw=1350&sh=1000&sm=fit",
      "website_link": "http://www.anastasiabeverlyhills.com/liquid-lipstick/liquid-lipstick.html",
      "description": "An intensely pigmented, cult-favorite liquid formula that delivers a rich, long-wearing matte look to lips. Use the flat sponge-tip applicator to apply Anastasia Beverly Hills Liquid Lipstick with precision for an unforgettable look.",
      "rating": 4.4,
    },{
      "name": "Sun Dipped Glow Kit",
      "price": "$40.00",
      "image_link": "http://www.anastasiabeverlyhills.com/dw/image/v2/BBLL_PRD/on/demandware.static/-/Sites-anastasia-master-catalog/default/dwfc30d1ee/images/2017%20New%20Logo/FACE/Glow%20Kits/ABH01-18158-sun-dipped/2000%20x%202000/abh-sun-dipped-glow-kit.jpg?sw=1350&sh=1000&sm=fit",
      "website_link": "http://www.anastasiabeverlyhills.com/glow-kit-sun-dipped/ABH01-18158.html#q=Sun%2BDipped%2BGlow%2BKit&lang=default&start=1",
      "description": "A collection of four metallic powder highlighters for intense luminosity. Layer shades of Anastasia Beverly Hills Glow Kit, or wear them separately, on the face and body for a radiant glow. Ideal for use with Brush #23. ",
      "rating": 4.8,
    }, {
      "name": "Brow Wiz Pencil",
      "price": "$21.00",
      "image_link": "http://www.anastasiabeverlyhills.com/dw/image/v2/BBLL_PRD/on/demandware.static/-/Sites-anastasia-master-catalog/default/dw5ff96acd/images/2017%20New%20Logo/BROWS/Brow%20Wiz/ABH01-86003-dark-brown/2000%20x%202000/abh-dark-brown-brow-wiz.jpg?sw=1350&sh=1000&sm=fit",
      "website_link": "http://www.anastasiabeverlyhills.com/brow-wiz/brow-wiz.html#q=Brow%2BWiz%2BPencil&lang=default&start=1",
      "description": "An award-winning ultra-slim, retractable pencil that creates precise, hair-like strokes. Use Anastasia Beverly Hills Brow Wiz's fine tip to spot-fill areas where brow hair is sparse, and the custom spooley end to blend for a flawless finish.",
      "rating": 4.7,
    }, {
      "name": "Dipbrow Pomade",
      "price": "$18.00",
      "image_link": "http://www.anastasiabeverlyhills.com/dw/image/v2/BBLL_PRD/on/demandware.static/-/Sites-anastasia-master-catalog/default/dw231ab3a8/images/products/BROWS/Dipbrow/Dipbrow-Medium-Brown/dipbrow-medium-brown.jpg?sw=1350&sh=1000&sm=fit",
      "website_link": "http://www.anastasiabeverlyhills.com/dipbrow-pomade-waterproof-color-brow-sculpt/dipbrow-pomade.html",
      "description": "An award-winning waterproof, multitasking, and buildable matte pomade that stays put. Apply and blend a small amount of Anastasia Beverly Hills Dipbrow Pomade with an angled brow brush to effortlessly outline, fill, and texturize brows.",
      "rating": 4.7,
    }, {
      "name": "Modern Renaissance Eyeshadow Palette",
      "price": "$42.00",
      "image_link": "http://www.anastasiabeverlyhills.com/dw/image/v2/BBLL_PRD/on/demandware.static/-/Sites-anastasia-master-catalog/default/dw3cf10410/images/2017%20New%20Logo/EYES/Eye%20Shadow%20Palette/ABH01-18170-modern-renaissance/2000%20x%202000/abh-modern-renaissance-eye-shadow-palette.jpg?sw=348&sh=348&sm=fit",
      "website_link": "http://www.anastasiabeverlyhills.com/modern-renaissance-palette/ABH01-18170.html#q=Modern%2BRenaissance%2BEyeshadow%2BPalette&lang=default&start=1",
      "description": "An essential eye shadow collection featuring 14 shades, including neutral and berry tones. Use Anastasia Beverly Hills first permanent palette, Modern Renaissance to create endless looks for daytime and evening. ",
      "rating": 4.8,
    }
  ],
    "Too Faced": [{
      "name": "Born This Way Absolute Perfection Foundation",
      "price": "$39.00",
      "image_link": "https://d210vlyat54t3c.cloudfront.net/media/transfer/img/web_bornthisway_foundation_closed_5_porcelain.jpg",
      "website_link": "https://www.toofaced.com/p/foundations/born-this-way-foundation/porcelain-very-fair-with-neutral-undertones/",
      "description": "Born This Way is an oil-free foundation that masterfully diffuses the line between makeup and skin. For coverage so undetectable, you can’t see the makeup and you can’t see imperfections—all that’s left is naturally radiant skin that looks like you were Born This Way.",
      "rating": "4.0",
    }, {
      "name": "Sketch Marker Liquid Eyeliner",
      "price": "$20.00",
      "image_link": "https://d210vlyat54t3c.cloudfront.net/media/transfer/img/web_sketchmarker_closed_deepblack.jpg",
      "website_link": "https://www.toofaced.com/p/eyeliner/sketch-marker/black/",
      "description": "Sketch Marker is an advanced liquid eyeliner inspired by Japanese Calligraphy Pens. Its formula acts as an artist’s drawing ink, created to be smooth, vivid, waterproof and ideal for lining eyes. The flexible tip allows you to create paintbrush-like strokes for daytime to dramatic cat eyes and everything in between.",
      "rating": "4.0",
    }, {
      "name": "Chocolate Soleil Matte Bronzer",
      "price": "$30.00",
      "image_link": "https://d210vlyat54t3c.cloudfront.net/media/transfer/img/web_chocolatesoleil_open.jpg",
      "website_link": "https://www.toofaced.com/p/bronzers/chocolate-soleil/",
      "description": "Go ahead, indulge yourself. You won’t add pounds when you dip into our antioxidant-rich, cocoa-licious, zero-calorie bronzer; just an irresistible, all-over deep tan.",
      "rating": 4.7,
    }, {
      "name": "Born This Way Naturally Radiant Concealer",
      "price": "$28.00",
      "image_link": "https://d210vlyat54t3c.cloudfront.net/media/transfer/img/web_bornthiswayconcealer_closed_1_veryfair.jpg",
      "website_link": "https://www.toofaced.com/p/concealers/born-this-way-concealer/very-fair-with-rosy-undertones/",
      "description": "Instantly hide imperfections, vanish the appearance of dark circles, and blur the look of lines and wrinkles for complete coverage so undetectable, they’ll think you were Born This Way.",
      "rating": 4.2,
    }, {
      "name": "Better Than Sex Mascara",
      "price": "$23.00",
      "image_link": "https://d210vlyat54t3c.cloudfront.net/media/transfer/img/web_betterthansex_composite.jpg",
      "website_link": "https://www.toofaced.com/p/mascaras/better-than-sex-mascara/",
      "description": "Created during a holy grail quest to find a truly buildable mascara, Better Than Sex provides extreme volume and a more dramatic look with each coat. One coat of the carbon black, collagen-fueled formula and lashes are full, defined and stretched to unbelievable lengths. Two coats and lashes are even more luscious, curled, and dramatic. Three coats and achieve the most intense black, oversized, multidimensional lashes possible! The Hourglass-Shaped brush unlocks the formula to create the perfect mascara that volumizes, lifts and coats both tops and bottoms of every little lash—with no lash left behind. A mascara so amazing…it’s Better Than Sex!",
      "rating": 4.3,
    }, ],
    "Urban Decay": [{
      "name": "Naked Skin Weightless Ultra Definition Liquid Makeup",
      "price": "$40.00",
      "image_link": "https://www.urbandecay.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-urbandecay-master-catalog/default/dw1ecceaef/ProductImages/Face/NakedSkinLiquid/Master_nakedfoundation_alt1.jpg?sw=1000&sh=1000&sm=fit",
      "website_link": "https://www.urbandecay.com/naked-skin-liquid-makeup-from-urban-decay/334.html#q=Naked+Skin+Weightless+Ultra+Definition+Liquid+Makeup&start=1",
      "description": "It feels like wearing nothing, yet Naked Skin Liquid Makeup transforms your complexion. Skin looks natural, illuminated and bright with a luminous demi-matte finish: like the beautiful skin you were born with. Light-diffusing spheres provide a visible reduction in the appearance of fine lines and wrinkles, blurring imperfections for beautifully perfected, ultra definition skin that looks completely real. ",
      "rating": 4.4,
    }, {
      "name": "Naked Heat Palette",
      "price": "$54.00",
      "image_link": "https://www.urbandecay.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-urbandecay-master-catalog/default/dw0ea9c17c/ProductImages/Palettes/NakedHeat/3605971553936_naked_heat_alt1.jpg?sw=1000&sh=1000&sm=fit",
      "website_link": "https://www.urbandecay.com/naked-heat-eyeshadow-palette/ud854.html#q=Naked+Heat+Palette&start=1",
      "description": "Give in to the heat of the moment with 12 can't-live-without, amber - hued neutrals - including warm browns, burnt oranges, and rich siennas. The most shade - driven Naked Palette UD has ever done, this palette takes Naked in a whole new direction. From a super - smooth red - brown matte and a glimmering copper to a deep, shifty bronze, this palette has everything you need to create sultry daytime looks, intensely smoky nighttime looks and everything in between.",
      "rating": 4.8,
    }, {
      "name": "Original Eyeshadow Primer Potion",
      "price": "$22.00",
      "image_link": "https://www.urbandecay.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-urbandecay-master-catalog/default/dw772d4764/ProductImages/Eyes/ESPP%202015/3605970936099_espp_original_alt2.jpg?sw=570&sh=570&sm=fit",
      "website_link": "https://www.urbandecay.com/eyeshadow-primer-potion/UD515.html#q=Original+Eyeshadow+Primer+Potion&start=1",
      "description": "The number-one primer for indestructible, all-day eyeshadow, our legendary Eyeshadow Primer Potion delivers everything you could possibly want in an eye primer: No creasing. More vibrant color. Smoother application.",
      "rating": 4.7,
    }, {
      "name": "24/7 Glide-On Eye Pencil",
      "price": "$20.00",
      "image_link": "https://www.urbandecay.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-urbandecay-master-catalog/default/dwd10af543/ProductImages/Eyes/247EyePencil/Master_247eyepencil.jpg?sw=570&sh=570&sm=fit",
      "website_link": "https://www.urbandecay.com/24-7-glide-on-eye-pencil/122.html#q=24%2F7+Glide-On+Eye+Pencil&start=4",
      "description": "Creamy, long-lasting, award-winning AND waterproof, 24/7 Glide-On Eye Pencil is the best eye pencil ever, ever, ever! Urban Decay's velvety-soft 24/7 formula stays creamy for blending (about 30 seconds), then dries down to a long-lasting finish that WILL NOT budge. ",
      "rating": 4.4,
    }, {
      "name": "Naked Skin Weightless Complete Coverage Concealer",
      "price": "$29.00",
      "image_link": "https://www.urbandecay.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-urbandecay-master-catalog/default/dw0a21c845/ProductImages/Face/NakedConcealer/Master_nakedconcealer_alt1.jpg?sw=570&sh=570&sm=fit",
      "website_link": "https://www.urbandecay.com/naked-skin-weightless-complete-coverage-concealer-by-urban-decay/503.html#q=Naked+Skin+Weightless+Complete+Coverage+Concealer&start=1",
      "description": "Cover imperfections without looking covered up. Urban Decay's Naked Skin Weightless Complete Coverage Concealer gives you buildable, even coverage with a luminous, demi-matte finish. Ultra lightweight, this high-tech formula melds like a second skin to give you full coverage in an instant.",
      "rating": 4.5,
    }, ],
  };
  response.setHeader('Content-Type', 'application/json');
  response.write(JSON.stringify(data));
  response.end();
});

server.listen(3000);
